### ISSUE TITLE
Resizing issues for vim

### ISSUE THREAD

**Issue by leimath** [terminalpp/terminalpp#33]
On my quest to find a decent terminal to use vim on windows, I managed to replicate https://github.com/microsoft/terminal/issues/13184 on terminalpp.

>    version:    0.8.4
    commit:     6444618c981a737a63039110add5a4e1d282156f
    platform:   Windows(native) 64 MSVC 19.28.29914.0 release
    build time: 2021-05-12T19:10:37Z
    Shell: pwsh(7)

-----

Steps to replicate (from default config):

1: Install `vim`, open terminalpp.
2. Spam bunch of junk. Any text to create some text history. (See video attached).
3. Type `vim` command and go to `INSERT` mode.
4. Create some text . Just keep spamming.
5. Resize with mouse.
6. `:q!` to quit. (Notice the broken interface now!)
7. Press `ALT + Enter` to maximize and get the glitched text.
8. Press `ALT + Enter` again to resize back to normal size and have it further broken in diagonals.

<img src="https://user-images.githubusercontent.com/96306150/172655826-4afe1f8b-802e-462f-901d-0128fe10ffd9.png" width="550" height="379" />
This is the glitched text of step 6.

https://user-images.githubusercontent.com/96306150/172657462-a8a973ad-4314-4389-a0b2-923a04839b0d.mp4

-----

**Comment by zduka** [comment]
Hi, apologies for longer delay - I am swamped at work:) I'm sorry about the issues, but unfortunately I do not think I can fix that easily in Tpp. The problem is almost certainly in the way Windows translates the Win32 Terminal API to the VT sequences that tpp uses. Since the new Windows terminal uses them too, you will observe the same issues there. If you try tpp, WSL with the bypass and vim there, then the problem no longer exists (checked), which is because the bypass completely bypasses the Win32 terminal API layer (it might still affect the Windows Terminal since I do not recall them using any bypass). 

Even writing a bypass for powershell, which might be possible would sadly not help you with `vim`, a quick internet check (I am not a vim user myself) revealed that it uses Win32 APIs natively in the windows version, so there would be nothing to bypass. 

If my description of the problem is not accurate, please feel free to reopen the issue! Thanks a lot!
