### ISSUE TITLE
Contextual menu on mouse right click not working

### ISSUE THREAD

**Issue by Taskkill** [terminalpp/terminalpp#7]
Setup:
Ubuntu 19.10

How to reproduce:
Click with right mouse button.

What happens:
Nothing.

What should happen:
Contextual menu should appear. At least I believe so.

**Comment by zduka** [comment]
This is expected behavior. Not all platforms provide right-click context menu and as of now, the right mouse click is reported to the application running in the terminal which can choose to react on the event. 

Furthermore, there is no context menu terminalpp can offer now, once there is (and once shortcuts are configurable) there might be an option to show context menu on right click, but it won't be default behavior.
